version: '3'
services:
  homeassistant:
    container_name: ha
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - /home/raj/.homeassistant:/config
      - /home/raj/home-assistant/homeassistant/components/hdmi_cec:/config/custom_components/hdmi_cec
    environment:
      - TZ=America/Chicago
      - WHEELS_LINKS=https://wheels.hass.io/alpine-3.12/amd64/
    restart: always
    network_mode: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
  vouch-proxy:
    container_name: vouch
    image: voucher/vouch-proxy
    restart: always
    volumes:
      - /etc/vouch-proxy:/config
    ports:
      - "9090:9090"
